services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: commodity_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/commodity-tracker/data
      - ./scripts:/commodity-tracker/scripts
    networks:
      - etl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chinook -d chinook"]  
      interval: 10s
      timeout:  5s
      retries: 5    
  
  extractor:
    image: etl-py:latest
    depends_on: 
      - postgres
    volumes:
      - ./data:/commodity-tracker/data
      - ./scripts:/commodity-tracker/scripts
    networks:
      - etl-network  

networks:
  etl-network:
    driver: bridge

volumes:
  pgdata: